### ISSUE TITLE
Fix degenerate case checks

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#103]
They don't seem degenerate any more.  I think the changes to the data.raw scrips I made in #99 changed the datasets. (These changes were to make the datasets all of class `caretList`, which is now needed for `caretEnsemble`.)

We probably need to fix #102 first.

**Comment by zachmayer** [comment]
Can I close this, or do we still need to fix it?

**Comment by jknowles** [comment]
This is fixed in predict.caretEnsemble I believe.
