### ISSUE TITLE
caretList() does not support custom Caret models

### ISSUE THREAD

**Issue by nkurz** [zachmayer/caretEnsemble#109]
https://github.com/zachmayer/caretEnsemble/blob/master/R%2FcaretList.R#L46

``` R
   methodCheck <- function(x){
     all_models <- unique(modelLookup()$model)
     bad_models <- setdiff(x, all_models)
     if(length(bad_models)>0){
       msg <- paste0("'", paste(bad_models, collapse="', '"), "'")
       stop(paste('The following models are not valid caret models:', msg))
     }
     return(invisible(NULL))
   }
```

Caret allows the user to pass either a string or an object that supports the required methods: 
http://topepo.github.io/caret/custom_models.html

It would be preferable if any model considered legal by Caret is acceptable for caretList().

The best solution might be to refactor Caret's train.default (https://github.com/topepo/caret/blob/5b024079ba098d954e036613a17628729b5c65f7/pkg/caret/R/train.default.R) to pull out the validation check so it can be used by caretList() and stays in sync.   

If this approach is taken, returned train$method should be changed from 'custom' to something user supplied or automatically generated.   Might be good for error reporting to have the checkInstall() included in the validation.  Less preferably, the code checking for minNames could be duplicated.

Alternatively, one could omit the check if an object is passed and let the train.object() method accept whatever it wants.   This last may seem less desirable, but would allow for Caret extensions that allow alternative specifications --- as in the case of caretEnsemble that wants to allow a caretStack as a submodel.

**Comment by zachmayer** [comment]
I believe custom models are now supported but I will check

**Comment by zachmayer** [comment]
I have verified that custom models work.  Use `caretEnsemble::greedyMSE_caret()` as a template for your custom models, and then pass them (as a list of caretModelSpec's) to `tuneList`.

**Comment by zachmayer** [comment]
https://github.com/zachmayer/caretEnsemble/pull/310 has a test to verify custom model support.  You can use that test as a template for your own custom models.
