### ISSUE TITLE
Nested cross-validation

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#117]
It'd be nice to evaluate the ensemble on a separate test set than the one used to make the ensemble.

**Comment by zachmayer** [comment]
@rlesca01 If you want to incorporate this into caretEnsemble, feel free to send a PR.

Otherwise, Jared or I will give it a shot soonish.

**Comment by rlesca01** [comment]
Hi Zach, yeah I'll take a stab at this and send over a PR, mostly I need to add some tests to the code I have.
