### ISSUE TITLE
Investigate using data.table internally to save RAM

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#130]
We're passing around a lot of datasets here, and it would be nice if they didn't get copied each time.  We may also want to look into doing this in caret too.

**Comment by jrowen** [comment]
Somewhat related, `caretList` generates an error if `data` is a `data.table`.  A quick fix appears to be using `setDF` to convert `data` to a `data.frame`.

**Comment by zachmayer** [comment]
done in 4.0
