### ISSUE TITLE
caretEnsemble does not support createTimeSlices traincontrol method

### ISSUE THREAD

**Issue by swarnavamitra21** [zachmayer/caretEnsemble#134]
When ever I try to train my model by using createTimeSlices traincontrol method I get an error, caretEnsemble does not support createTimeSlices traincontrol method

**Comment by jknowles** [comment]
Can you please provide a minimal working example so that we can investigate how to add this functionality?

**Comment by swarnavamitra21** [comment]
Hi this is my trainControl function 


library(caret)

myTimeControl <- trainControl(method = "timeslice", initialWindow =800,horizon =200, fixedWindow = TRUE,savePredictions=TRUE)



and this is the error message I get when trying to ensemble them using time slice CV method 


model_list_big <- caretList(
  Class~., data=TrainingSet,
  trControl=myTimeControl,
  metric='Accuracy',
  methodList=c('glm', 'rpart'),
  tuneList=list(
    rf1=caretModelSpec(method='rf', tuneGrid=data.frame(.mtry=2)),
    rf2=caretModelSpec(method='rf', tuneGrid=data.frame(.mtry=10), preProcess='pca'),
    nn=caretModelSpec(method='nnet', tuneLength=2, trace=FALSE)
  )
)



Error in trControlCheck(x = trControl, y = target) : 
  caretList does not currently know how to handle cross-validation method='timeslice'. Please specify trControl$index manually
In addition: Warning message:
In trControlCheck(x = trControl, y = target) :
  indexes not defined in trControl.  Attempting to set them ourselves, so each model in the ensemble will have the same resampling indexes.

**Comment by zachmayer** [comment]
caretList doesn't support timecv yet.




You need to manually set index and indexOut in your trainControl object.  You can use createTimeSlices to do this.



—
