### ISSUE TITLE
Auto import for the predict method

### ISSUE THREAD

**Issue by jknowles** [zachmayer/caretEnsemble#14]
If you ensemble a series of models using external packages (e.g. `mda` or `glmnet`) and then clear your workspace and R session and load the `caretEnsemble` object and attempt to use the `predict` method, it fails.

This is because the `predict` method for each individual model type is not necessarily in the namespace. The `predict.caretEnsemble` should be able to identify and import the `predict` methods necessary to generate predictions for each model type to be ensembled.

**Comment by zachmayer** [comment]
I pinged Prof. Hastie about this, and he said it's on his list, but he's not sure when he'll get to it.

Perhaps some industrious person could submit a patch to him.  I'm note sure where the mda and glment source code lives.

**Comment by zachmayer** [comment]
predict should be using s3 classes now
