### ISSUE TITLE
Consider replacing do.call with something else

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#155]

**Comment by jangorecki** [comment]
why not build the call instead?
```r
as.call(list(as.name(fun.name), as.name(var.name))
```

**Comment by zachmayer** [comment]
Before I do anything here, I would like to run some tests with large datasets and assess how much of a problem this is.

**Comment by zachmayer** [comment]
closed in favor of https://github.com/zachmayer/caretEnsemble/issues/309
