### ISSUE TITLE
gbm fails when using caretList but doesn't when using train directly

### ISSUE THREAD

**Issue by farbodr** [zachmayer/caretEnsemble#159]
I'm using the data from Liberty Mutual competition on Kaggle and every time this call to caretList fails
 with message:

Something is wrong; all the RMSE metric values are missing:
      RMSE        Rsquared  
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :1     NA's   :1    

Here is the code that generate this error. Same result if I omit tuneGrid param?
```{r}
gbm.tune.grid = expand.grid(interaction.depth = 3,
                                      n.trees = 500,
                                    shrinkage = 0.1,
                               n.minobsinnode = 40)

model.list <- caretList(
  Hazard ~ ., data = select(trainDF, -Id),
  metric='RMSE',
  trControl= trainControl("cv", number = 10),
  tuneList=list(
    gbm=caretModelSpec(method = 'gbm', verbose=T, tuneGrid=gbm.tune.grid),
    xgblinear=caretModelSpec(method='xgbLinear', trace=T, verbose=T, tuneGrid=xgbl.tune.grid),
    ridge=caretModelSpec(method='ridge', trace=T, verbose=T, tuneLength=5),
    xgbtree=caretModelSpec(method='xgbTree', trace=T, verbose=T, tuneLength=5),
    cube=caretModelSpec(moethod='enet', trace=T, verbose=T, tuneGrid=cubist.tune.grid),
    enet=caretModelSpec(moethod='enet', trace=T, verbose=T, tuneLength=5),
    mars=caretModelSpec(method='bagEarth', trace=T, verbose=T, tuneLength=5)
  )
)
```{r}
but using same data if I call train as below directly it finishes with no error
```{r}
gbmFit1 <- train(Hazard ~ ., data = select(trainDF, -Id),
                 method = "gbm",
                 trControl = trainControl("cv", number = 10),
                  tuneGrid = expand.grid(interaction.depth = 3,
                                                   n.trees = 500,
                                                 shrinkage = 0.1,
                                            n.minobsinnode = 40))
```{r}

**Comment by zachmayer** [comment]
Please provide minimal example that produces the bug, using a standard dataset in R, e.g the iris dataset.




Minimal means cut out all the irrelevant code you can, while preserving the bug. This will go a long way towards identifying what when wrong.




Also just try calling caret::train



—

**Comment by farbodr** [comment]
Thank you for your reply. There was another issue with my code that cause this. 

Thanks again,
FR

**Comment by jknowles** [comment]
This should be closed now.

**Comment by dearkafka** [comment]
had same problem with similar code, I had verbose = T in caretList(. After removing everything worked fine
