### ISSUE TITLE
Is the ROC metric available in this package?

### ISSUE THREAD

**Issue by terrytangyuan** [zachmayer/caretEnsemble#161]
I am not sure if you have noticed this but my friend tried this package and found the ROC/AUC does not work for her. Has this been implemented? She tried a couple of times. 

Warning message:
In train.default(predobs$preds, predobs$obs, ...) :
 The metric "ROC" was not in the result set. Accuracy will be used instead.

**Comment by zachmayer** [comment]
This is probably a problem with your call to caret::train.  Please provide a reproducible example and I'll help you debug it.



—

**Comment by terrytangyuan** [comment]
Yeah it's a problem in `caret` package. I've posted a issue there instead [https://github.com/topepo/caret/issues/218]. Thanks.
