### ISSUE TITLE
Better standard errors for predictions

### ISSUE THREAD

**Issue by jknowles** [zachmayer/caretEnsemble#162]
I am increasingly concerned about reporting the "standard error" for the predictions, which currently is really just a measure of model disagreement. It doesn't take into account the uncertainty within any given model about the predicted value for each case. This is because not all `train` objects produce a prediction interval. 

Recently I have come across [Platt Scaling](https://en.wikipedia.org/wiki/Platt_scaling) as a method to deal with this issue. One option we could consider for `predict` would be to have the user request different types of intervals (model disagreement, platt scaled, none) and then do the platt scaling behind the scenes. 

However, this might be a better addition to `caret` itself, instead of to `caretEnsemble` -- what do you think?

**Comment by zachmayer** [comment]
I think this makes sense to add to caret— once caret supports prediction intervals well (with some way of estimating them for models that don't produce them), we can decide how best to combine them.

**Comment by jknowles** [comment]
Is someone actively working on that in caret -- or do you think that contribution would be welcomed?

**Comment by zachmayer** [comment]
It's under discussion here, but sounds like a big effort: https://github.com/topepo/caret/issues/187

**Comment by jknowles** [comment]
That definitely solves it for one case -- where probabilities are returned -- but I'm not sure if it will add functionality to estimate probabilities for models in which probabilities are not returned -- which Platt Scaling is intended to do. I'll follow the discussion there and wait to see how things shake out. I'll suggest any changes to `caret` though instead of `caretEnsemble`.

**Comment by zachmayer** [comment]
I agree— I think platt scaling would be a useful addition to caret, so all probability models at least can return prediction intervals.
