### ISSUE TITLE
Caruana et. al.'s papers

### ISSUE THREAD

**Issue by cancandan** [zachmayer/caretEnsemble#164]
I came across the project [pyensemble] (https://github.com/dclambert/pyensemble) that implements all features decribed in both papers 04 and 06 of Caruana et. al. I thought about doing the same with caret and then found about caretEnsemble :) I'm still examining the code but wanted to ask the project owner: Does caretEnsemble implement those features or is it planned or will it be different?

**Comment by zachmayer** [comment]
Which features are you looking for?  Right now we enable 2 methods of combining models:
1. Greedy forward selection, as described in Caruana et. al. 2004
2. Model-based stacking (e.g. with glm or any other caret model)

Personally, I like 2 a lot better.  The model weights yielded by a glm often tend to be very similar to those yielded by greedy forward selection, and I like the flexibility of being able to use any caret model for stacking.

Feel free to open new issues with specific feature requests.

**Comment by zachmayer** [comment]
Looking at the readme from the python package, I'd say we implement the following:
[x] internal cross validation - yup, internal grid-search too.
[x] bagged ensembling - yes, just used `rf` or `treebag` methods in caretStack.
[x] initialization with the best models - sort of.  We grid search each model and only use the best grid-search results for the ensemble.
[x] pruning of the worst models prior to selection - sort of.  We grid search each model and only use the best grid-search results for the ensemble.
[ ] sampling with replacement of the model candidates. - I don't think we do this.  This might be a good feature to add to the `caretEnsemble` function.

**Comment by zachmayer** [comment]
[Also, take a look at our vignette](https://htmlpreview.github.io/?https://github.com/zachmayer/caretEnsemble/blob/master/inst/doc/caretEnsemble-intro.html)

**Comment by cancandan** [comment]
I see. I'm trying to understand inner cross validation in 06 [paper] (http://www.niculescu-mizil.org/papers/enssel_most_long.pdf). In section "6 Cross-Validated Ensemble Selection" author says this 
> "A cross-validated model is created by training a model
for each fold with the same model parameters. If there are
5 folds, there will be 5 individual models (each trained on
4000 points) that are ‘siblings’ 

and later
> when selection adds a cross-validated
model to a growing ensemble, it really adds 5 different models
of the same model type to the ensemble, each of which
receives the same weight in the ensemble average

So does this add "cv number" (say 5), of models to the ensemble?
```
tuneList=list(
    rf1=caretModelSpec(method="rf", tuneGrid=data.frame(.mtry=2)),
...
```
I think I'm confused..

**Comment by zachmayer** [comment]
I see.  They're taking a different approach to CV than `caretEnsemble`.

Their approach: Train 5 models (one on each CV fold), and then average their predictions on new data.
Our approach:   Train 5 models (one on each CV fold), and then train a final, 6th model on the full dataset.  Use the 6th model for prediction.

Our approach results in smaller "libraries" of models and also lets us tune the 6th model's hyperparameters, using the CV folds from the first 5 models.

**Comment by cancandan** [comment]
Yes his approach does not throw away trained models at least not in that stage, which raises the question how those two approaches compare in general.

**Comment by zachmayer** [comment]
I haven't directly compared them, but I personally like my approach better because I can build on top of the caret packages, which throws out the CV models after training.

It also makes sense to me in that un-correlated models tend to add the most to an ensemble, and different variants of the same model (either trained in different folds or with slightly altered tuning parameters) will tend to yield very similar results.

**Comment by cancandan** [comment]
I think leaving model selection to the second stage is the whole purpose of ensembling. Also throwing away models might be suboptimal at least for high variance models like trees.

**Comment by zachmayer** [comment]
You may be right.  Currently, caretEnsemble uses a 2-step model selection approach: grid search to select hyperparameters, followed by ensembling of the best grid-searched models.  If you'd prefer to do both steps at once you can make many individual models, each with a single set of tuning parameters (a tuneGrid with one row).  The final model will then be an ensemble of all the individual sub-models, with no grid search prior to ensembling.  The individual models for each cv-fold will still get thrown out, as you currently can't save those through `caret::train`.

You can also reduce the variance of individual models like trees through bagging or random forests.

You should also check out the [mlr](https://github.com/mlr-org/mlr) and [mlrMBO](https://github.com/berndbischl/mlrMBO) packages, which take slightly different approaches.
