### ISSUE TITLE
Inconsistent handling of predict functions when newdata contains an NA

### ISSUE THREAD

**Issue by jknowles** [zachmayer/caretEnsemble#165]
When the user passes a newdata object that contains `NA` values, sometimes the predict function will fail and other times it will return a valid result set. This is due to the different ways that the underlying methods to the `train` objects handle missing values in the predicted cases. We need to find a way to make this consistent.

**Comment by jknowles** [comment]
I think this is best fixed in train. It would require a substantial overhaul of the way both `predict.caretList` and `predict.caretEnsemble` work, which would be slower and when `predict.train` is modified to use `na.pass` it would be unnecessary. I'm fine with simply documenting that `newdata` cannot have NA values and throwing an error and asking the user to pre-process this.

**Comment by zachmayer** [comment]
Works for me

**Comment by jknowles** [comment]
Alright great. I will have a pull request shortly that fixes a lot of the outstanding issues with the predict methods that we have already discussed and documents these changes.

**Comment by jknowles** [comment]
I think this was closed by #167
