### ISSUE TITLE
predict.caretEnsemble defaults type='prob' which errors for RF and GBM

### ISSUE THREAD

**Issue by flylo** [zachmayer/caretEnsemble#171]
For tree models where finding the probability of a positive isn't possible, it's impossible to use the predict methods for ensembles, stacks, or lists.  No matter what I do, I only get the following error:

Error in `[.data.frame`(out, , obsLevels, drop = FALSE) : 
  undefined columns selected

I'm getting the same issue as [this SO post](http://stackoverflow.com/questions/30522709/how-to-predict-on-a-new-dataset-using-caretensemble-package-in-r).   His model isn't working because random forests don't support predict.train(...type='prob')

**Comment by jknowles** [comment]
This is really hard to diagnose without a [minimal reproducible example](http://stackoverflow.com/a/5963610/345660). As @zachmayer noted on the original SO post, please provide one so we can debug the error and make a precise patch. I think this actually has to do with some changes to the underlying `caret` API.

**Comment by jknowles** [comment]
Reported over in topepo/caret#274
