### ISSUE TITLE
caret 6.0-64 breaks caretEnsemble

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#180]
Email from max:
```
I made some changes to caret and it is violating one of the
caretEnsemble’s tests. I suspect that

   predict(mod)

is being used without `newdata`. I’ve attached the current version. Can
you confirm?
```

**Comment by Mosquito00** [comment]
Hello zachmayer, 

Thank you. 

Where can we find the new version?

**Comment by zachmayer** [comment]
Master branch here: https://github.com/topepo/caret/tree/master/pkg/caret

**Comment by zachmayer** [comment]
This commit for future reference: https://github.com/topepo/caret/tree/c2745556371c69d4ed62c560c45647702c604c82/pkg/caret

**Comment by zachmayer** [comment]
Fix is here: https://github.com/zachmayer/caretEnsemble/pull/181

**Comment by zachmayer** [comment]
Actually that fix may not fix the new issue.  We'll see.

**Comment by jknowles** [comment]
I don't think that'll fix the issue @zachmayer. I think the error is in some of my tests. Let me pull it down and see what I can change.

**Comment by zachmayer** [comment]
@jknowles Yeah, I think this fixes a different issue.  I think it's time to clean up and do a new CRAN release.

**Comment by jknowles** [comment]
Agreed. I'll work on fixing the unit tests and send a PR soon. Then we can think about anything else we should do pre-release.

**Comment by jknowles** [comment]
@zachmayer I think this might be localized to an issue with `predict.gbm` -- I'm testing that theory now.
