### ISSUE TITLE
CRAN checks failing 

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#184]
https://cran.r-project.org/web/checks/check_results_caretEnsemble.html

I just got this email from CRAN:
>Dear maintainer,

>As you were already informed several weeks ago, your package currently
fails in its tests: see
><https://CRAN.R-project.org/web/checks/check_results_caretEnsemble.html>
for all problems that need fixing.

>We really need a fixed version as soon as possible.

>Can you pls provide a fixed version before 2016-02-13?

>Best

>-k

Lets fix the travis build and ship to CRAN asap.

**Comment by jknowles** [comment]
I think this is related in part to this: https://github.com/topepo/caret/issues/347

We should decide which way to fix that and then make the changes necessary for CRAN.

**Comment by zachmayer** [comment]
fixed!
