### ISSUE TITLE
Class predictions from ensemble classifiers are reversed

### ISSUE THREAD

**Issue by eric-czech** [zachmayer/caretEnsemble#189]
I've been banging my head against this as I've run into it with several datasets now, but I think I've got a good reproducible to show how caretEnsemble seems to be flipping classes on class label predictions (it also seems to be a problem with predictions of probabilities, but it's easier to demonstrate with labels).

Am I doing something dumb here?  I can't see any reason why the predictions from an ensemble below would be inverted, as they appear to be below:

```
library(caretEnsemble)
library(caret)
set.seed(123)

# Create a very easily classifiable dataset with a binary response
X <- matrix(c(rnorm(n = 1500, mean=5), rnorm(n = 1500, mean=-5)), nrow = 1000, ncol=3)
y <- apply(X, 1, function(x) sum(x))
y <- sapply(1 / (1 + exp(-y)), function(p) factor(ifelse(runif(1) < p, 'yes', 'no'), levels=c('no', 'yes')))

# Split the above into training and test data 
train.idx <- createDataPartition(y)[[1]]

# Fit a glm to training data and examine the predictions on test data
glm.model <- train(X[train.idx,], y[train.idx], method='glm')
glm.pred <- predict(glm.model, newdata=X[-train.idx,], type='raw')
confusionMatrix(table(glm.pred, y[-train.idx]))

# The results are great, the glm model makes accurate out-of-sample predictions:
#      no   yes
# no  242   11
# yes   5   242

# Now do the same with a caret ensemble
model.list <- caretList(
  X[train.idx,], y[train.idx],
  trControl=trainControl(method="cv", number=10, savePredictions="final", classProbs=T),
  methodList=c("glmnet", "rda", "rf")
)
ens.model <- caretEnsemble(model.list)
ens.pred <- predict(ens.model, newdata=X[-train.idx,], type='raw')
confusionMatrix(table(ens.pred, y[-train.idx]))

# Now, somehow the labels seem to getting reversed on predicted classes:
#      no yes
# no    6 242
# yes 241  11
```

**Comment by zachmayer** [comment]
We're probably always sorting the class labels alphabetically (which probably also flips the probabilities when you ask for them)

I'll look into fixing this, but in the meantime, try coding your classes as 0/1 or "X0" and "X1" and see if you get the same problem.

**Comment by eric-czech** [comment]
Makes sense.  I had given what you suggested a shot before with no such luck, but I believe I found the problem.

In [makePredObsMatrix (line 241)](https://github.com/zachmayer/caretEnsemble/blob/92a920dd746aed24cfce831c525c0a08960fdfea/R/helper_functions.R#L241) the following code was being used to select the positive class:

```positive <- as.character(unique(modelLibrary$obs)[2]) #IMPROVE THIS!```

The problem with that is that unique returns the values in order of appearance so a different positive class is potentially being selected for each training fold.  For example:

```
unique(factor(c('positive', 'negative')))[2] # = 'negative'
unique(factor(c('negative', 'positive')))[2] # = 'positive'
```

I sent this [PR](https://github.com/zachmayer/caretEnsemble/pull/190) your way with a fix and I'll reprise this much for the sake of documentation.

**Comment by eric-czech** [comment]
Fixed by [PR 190](https://github.com/zachmayer/caretEnsemble/pull/190)

**Comment by PoLabs** [comment]
I'm sorry, still a bit confused on this. I expect classes labeled 1 to be positive and correspond to the same idea of 'positive' between train and predict. Am I missing something? Results seem off: 
 ```
  bin        raw     train test
1:   1 0.27003313 0.6083062    0
2:   1 0.09121508 0.6644845    0
3:   1 0.19655306 0.6382583    0
4:   0 0.87132128 0.6431920    0
5:   0 0.72700835 0.6179814    0
6:   0 0.95342506 0.6922593    0
```

**Comment by JanVanIm** [comment]
I've got the same issue. Was the problem solved in the latest release ?

**Comment by PoLabs** [comment]
I'm using the latest GitHub install so I don't think so

**Comment by juanbretti** [comment]
Same issue here.

**Comment by breezedu** [comment]
lol, July 2019, I am having the same issue.

**Comment by varelasebastian** [comment]
also having the same issue...

**Comment by kilianshi** [comment]
Hello, it seems that the problem is not solved, or is it?

**Comment by zachmayer** [comment]
It looks like one instance of this was solved in 2016, but it appears to have regressed.  I don't currently have time to dig into this issue and fix it, but I would be very happy to review and merge a pull request!
