### ISSUE TITLE
Running svmRadial in parallel in caretStack?

### ISSUE THREAD

**Issue by sparcycram** [zachmayer/caretEnsemble#202]
svmRadial appears not to run in parallel in caretStack. When observing the resource monitor in windows svmRadial appears to only use 1 CPU even with allowParallel = TRUE. The other models in caretStack pam, parRF, dnn are running on multiple cpu's. 

Is this a known issue?

Thanks

**Comment by zachmayer** [comment]
`allowParallel = TRUE` is an argument to `caret::train`, so this is really a question for the [caret github page](https://github.com/topepo/caret).

`pam` and `dnn` both use your blas, so if you have openblas, accelerate, or another optimized blas library, thos algorithms will run in parallel regardless of whether you set `allowParallel = TRUE` or `allowParallel = FALSE`.  `parRF` creates (and then destroys) it's own parallel cluster.

svmRadial, on the other hand, is inherently serial.  There's no way to parallelize it.

`allowParallel`  therefore doesn't effect the base model at all.  It just controls whether the caret-based grid search and cross-validation is done serially or in parallel.  If you wish to run in parallel, you will need to install the [doParallel](https://cran.r-project.org/web/packages/doParallel/index.html) package, and [read the directions for how to use it](https://cran.r-project.org/web/packages/doParallel/vignettes/gettingstartedParallel.pdf).  Once you know what you're doing, you can start a parallel cluster, run caret or caretEnsemble code with allowParallel=TRUE, and do grid search in parallel.
