### ISSUE TITLE
Is the option metric = 'logLoss' available in train()?

### ISSUE THREAD

**Issue by randel** [zachmayer/caretEnsemble#203]
With `train()` in the `caret` package, there is an option `metric = "logLoss"`. But for `caretEnsemble`, using this option will always trigger the warning below. It seems that this option has been blocked? Any feedback would be really appreciated.

`The metric "logLoss" was not in the result set. ROC will be used instead.`

**Comment by zachmayer** [comment]
You need to pass a custom summaryFunction to trainControl that calculates log loss.

By default, caret::train only computes accuracy.

**Comment by randel** [comment]
Thanks for your help!
For anyone interested, [here](https://www.kaggle.com/c/otto-group-product-classification-challenge/forums/t/13064/caret-alternate-performance-measures/69102#post69102) is a workable function for log loss.

**Comment by zachmayer** [comment]
No problem, and thanks for the link!
