### ISSUE TITLE
mandatory deps for package check

### ISSUE THREAD

**Issue by jangorecki** [zachmayer/caretEnsemble#205]
any chance for a list of packages that are mandatory to run package check? I see the (impressive) list in travis yaml has all possible dependencies, but I would like to install as few as necessary to run R CMD check.

**Comment by zachmayer** [comment]
If you set the `NOT_CRAN` environment variable to `"false"`, it should run with the bare packages listed in the description file

**Comment by jangorecki** [comment]
It doesn't seems to help.
```
echo $NOT_CRAN
#false
R CMD check --no-manual --ignore-vignettes caretEnsemble_2.0.0.tar.gz 
```

```
* checking package dependencies ... NOTE
Packages suggested but not available for checking:
  ‘caTools’ ‘lintr’ ‘glmnet’ ‘e1071’ ‘pROC’ ‘mlbench’ ‘klaR’
...
* checking tests ...
  Running ‘testthat.R’
 ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  Calls: test_check ... eval -> suppressMessages -> withCallingHandlers -> library
  testthat results ================================================================
  OK: 301 SKIPPED: 28 FAILED: 7
  1. Error: caretList predictions (@test-caretList.R#98) 
  2. Error: Classification models (@test-caretList.R#276) 
  3. Error: We can stack classification models (@test-caretStack.R#30) 
  4. Error: Failure to calculate se occurs gracefully (@test-caretStack.R#60) 
  5. Error: We can extract resdiuals from caretEnsemble objects (@test-ensemble.R#42) 
  6. Error: We can ensemble regression models (@test-ensemble.R#88) 
  7. Error: It works for classification models (@test-ensemble.R#174) 
  
  Error: testthat unit tests failed
  Execution halted
```

I reproduced first fails from https://github.com/zachmayer/caretEnsemble/blob/master/tests/testthat/test-caretList.R#L98 interactively and it looks like some of suggested deps are required.
```r
expect_warning({
    models <- caretList(
      iris[, 1:2], iris[, 5],
      tuneLength=1, verbose=FALSE,
      methodList="rf", tuneList=list(nnet=caretModelSpec(method="nnet", trace=FALSE)),
      trControl=trainControl(
        method="cv",
        number=2, savePredictions="final",
        classProbs=FALSE)
      )
  })
#Error in requireNamespaceQuietStop("e1071") : package e1071 is required
```

**Comment by zachmayer** [comment]
Hmm I'll have to check the correct way to run tests as cran

**Comment by jangorecki** [comment]
Besides checking that it may be worth to have a list of really mandatory package on hand.

**Comment by zachmayer** [comment]
It should be the list that's installed in Travis-- if it's not I should prune down the list in travis.

**Comment by jangorecki** [comment]
You mean that all of suggested deps are required to pass the check? as the list in travis probably lists all deps, not necessarily all required for check.

**Comment by zachmayer** [comment]
Pretty sure they're all required for a full check, as not cran

**Comment by zachmayer** [comment]
I'll go through the travis file sometime, and make sure there's nothing there that isn't required for the unit tests or the vignettes.  I'm pretty sure that's already the minimal requirements, but will check when I have time.

In the meantime, you can see if you setup your environment variables to skip tests marked `skip_on_cran()`, which will let your run `R CMD CHECK` with just the dependencies in the DESCRIPTION file.

**Comment by jangorecki** [comment]
FYI: **at least** `caTools` and `lintr` suggested dependencies were not required to pass check with `--as-cran`.

**Comment by zachmayer** [comment]
Good to know— I will remove those from the travis file

**Comment by jangorecki** [comment]
To do not open new issue as this is still related to dependencies management. `rmarkdown` pkg is missing in suggested deps, when you try to build and check pkg without rmarkdown, just with knitr, it will end up with error.
