### ISSUE TITLE
Timeslices

### ISSUE THREAD

**Issue by sparcycram** [zachmayer/caretEnsemble#207]
Zack are you thinking of making timeslices available on caretEnsemble?

**Comment by zachmayer** [comment]
I assume you mean in caretList? I don't have much time to work on caretensemble right now, but I always welcome PRs!

I'll add support for them at some point in the future, but not soon.

**Comment by sparcycram** [comment]
Sorry meant caretList:) I am working on some timeseries data and just randomly splitting using createdatapartition so not optimal. 

PS thanks for the package though its done an impressive job

**Comment by zachmayer** [comment]
you can pass a trainControl to caretlist, and in that control you can include whatever indexes you want!  it works!

(if you find a case where it does not, please submit a test case!)
