### ISSUE TITLE
thanks! 

### ISSUE THREAD

**Issue by achekroud** [zachmayer/caretEnsemble#215]
Just wanted to say thanks for putting together such a great & well documented package. I wanted to tweet some thanks but couldn't find you on twitter! In any case, I'll be sure to spread the love & let people know about caretEnsemble as a super easy way into model ensembling.

**Comment by zachmayer** [comment]
Thank you for using the package!  I'm glad it was useful to you.

For future reference, here I am on twitter: https://twitter.com/ZacharyMayer (I'm not super active)
