### ISSUE TITLE
Different versions of caretEnsemble 2.0.0?

### ISSUE THREAD

**Issue by sparcycram** [zachmayer/caretEnsemble#216]
Zach I seem to have different versions of caretEnsemble both 2.0.0 both dated 2016-02-06

The first one has getBinaryTargetLevel in it and works with my code, the second doesn't and throws an error of  Error in eval(expr, envir, enclos) : object 'rda10' not found when trying to predict with a caretEnsemble object  as well as Error: could not find function "getBinaryTargetLevel". The issue has appeared on both windows different machines and Ubuntu. In the help pages getBinaryTargetLevel exist in the first one but not the second?

This is the first one that works

Package: caretEnsemble
Type: Package
Title: Ensembles of Caret Models
Version: 2.0.0
Date: 2016-02-06
Authors@R: c(person(c("Zachary", "A."), "Deane-Mayer", role = c("aut", "cre"),
    email = "zach.mayer@gmail.com"),
    person(c("Jared", "E."), "Knowles", role=c("aut"),
    email="jknowles@gmail.com"))
URL: https://github.com/zachmayer/caretEnsemble
BugReports: https://github.com/zachmayer/caretEnsemble/issues
Description: Functions for creating ensembles of caret models: caretList()
    and caretStack().  caretList() is a convenience function for fitting multiple
    caret::train() models to the same dataset. caretStack() will make linear or
    non-linear combinations of these models, using a caret::train() model as a
    meta-model, and caretEnsemble() will make a robust linear combination of
    models using a GLM.
Depends: R (>= 3.2.0)
Suggests: caTools, testthat, lintr, randomForest, glmnet, rpart,
        kernlab, nnet, e1071, ipred, pROC, knitr, mlbench, MASS, gbm,
        klaR, rmarkdown
Imports: methods, pbapply, ggplot2, digest, plyr, lattice, gridExtra,
        data.table, caret
License: MIT + file LICENSE
VignetteBuilder: knitr
RoxygenNote: 5.0.1
Author: Zachary A. Deane-Mayer [aut, cre],
  Jared E. Knowles [aut]
Maintainer: Zachary A. Deane-Mayer <zach.mayer@gmail.com>
Built: R 3.3.1; ; 2016-09-27 21:10:28 UTC; windows
RemoteType: github
RemoteHost: https://api.github.com
RemoteRepo: caretEnsemble
RemoteUsername: zachmayer
RemoteRef: master
RemoteSha: 63e2818e00e3458eb6b6156c1d51dee72426a192
GithubRepo: caretEnsemble
GithubUsername: zachmayer
GithubRef: master
GithubSHA1: 63e2818e00e3458eb6b6156c1d51dee72426a192

This one doesn't

Package: caretEnsemble
Type: Package
Title: Ensembles of Caret Models
Version: 2.0.0
Date: 2016-02-06
Authors@R: c(person(c("Zachary", "A."), "Deane-Mayer", role = c("aut", "cre"),
    email = "zach.mayer@gmail.com"),
    person(c("Jared", "E."), "Knowles", role=c("aut"),
    email="jknowles@gmail.com"))
URL: https://github.com/zachmayer/caretEnsemble
BugReports: https://github.com/zachmayer/caretEnsemble/issues
Description: Functions for creating ensembles of caret models: caretList
    and caretStack.  caretList is a convenience function for fitting multiple
    caret::train models to the same dataset. caretStack will make linear or
    non-linear combinations of these models, using a caret::train model as a
    meta-model, and caretEnsemble will make a robust linear combination of
    models using a glm.
Depends: R (>= 3.2.0)
Suggests: caTools, testthat, lintr, randomForest, glmnet, rpart,
        kernlab, nnet, e1071, ipred, pROC, knitr, mlbench, MASS, gbm,
        klaR
Imports: methods, pbapply, ggplot2, digest, plyr, lattice, gridExtra,
        data.table, caret
License: MIT + file LICENSE
VignetteBuilder: knitr
RoxygenNote: 5.0.1
NeedsCompilation: no
Packaged: 2016-02-06 16:06:12 UTC; zachary
Author: Zachary A. Deane-Mayer [aut, cre],
  Jared E. Knowles [aut]
Maintainer: Zachary A. Deane-Mayer <zach.mayer@gmail.com>
Repository: CRAN
Date/Publication: 2016-02-07 10:50:09
Built: R 3.3.1; ; 2016-10-01 17:21:47 UTC; unix

**Comment by zachmayer** [comment]
That's odd.  Did you install them both from CRAN?  Try the version on github: `devtools::install_github('zachmayer/caretEnsemble')`.

**Comment by sparcycram** [comment]
I installed the latest version from CRAN. This version is the one that causes the problem I think.

If I try to install the github version I get the following error.

Warning in install.packages :
  package ‘devtools::install_github('zachmayer/caretEnsemble')’ is not available (for R version 3.3.1)

If I use an old copy from R 3.2.4 or R3.2.5 and just copy it directly into the R3.3.1 library it runs and works and has the getBinaryTargetLevel functionality in it. Not sure why the CRAN version doesn't work as its not just the getBinaryTargetLevel that fails.

I'm up and running but not sure how anyone using R 3.3.1 is getting results with predict in CaretEnsemble?

**Comment by zachmayer** [comment]
Don't wrap it in install.packages.  Just run devtools::install

**Comment by sparcycram** [comment]
Thanks works 

Appears that the cran version is different.

**Comment by sparcycram** [comment]
If you install straight from github the correct package loads and works.

>devtools::install_github('zachmayer/caretEnsemble')

Thanks Zach
