### ISSUE TITLE
caretEnsemble breaks with new GBM

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#219]
Email from the GBM team:

> Hi!
> 
> We're coming up to a new release of gbm which considerably tidies the code and introduces a much stricter NAMESPACE.  As part of this we have unfortunately had to change the API, and it looks like it is breaking your package.  Would it be possible for you to take a look?
> 
> The new gbm is at
> 
> https://github.com/gbm-developers/gbm
> 
> Thanks,

I'll need to check against the new version and see what needs fixin'.

**Comment by sparcycram** [comment]
Are you having any luck with this. Unfortunately I can only add moral support. All I can say is caretEnsemble is extremely useful and gbm is one of the go to packages in ensembling.

**Comment by zachmayer** [comment]
Use the old GBM for now, until I can fix this.

**Comment by zachmayer** [comment]
seems to work now

**Comment by zachmayer** [comment]
or at least the new cran build worked: https://github.com/zachmayer/caretEnsemble/pull/247
