### ISSUE TITLE
Speeding up caretEnsemble with hardware?

### ISSUE THREAD

**Issue by sparcycram** [zachmayer/caretEnsemble#221]
Clock speed vs cores in caretEnsemble.

Zach do you have any advice here on the best way of speeding up caretEnsemble from a hardware point of view. 

I know its an open question but if one is running a set of models viz svm, parrf, gbm and glm for example, some of which can run in parallel and some can't. Where do you think the best speed improvement would be, clock speed, cache or cores?

Any thoughts appreciated.

**Comment by zachmayer** [comment]
More RAM is by far the most important requirement.  After that, more cores.

**Comment by zachmayer** [comment]
After that, faster cores, after that, probably more cache (but I really have no idea how cache helps in R).
