### ISSUE TITLE
varImp in caretStack

### ISSUE THREAD

**Issue by jeonghyunwoo** [zachmayer/caretEnsemble#224]
caretEnsemble object provides varImp.
But, caretStack object doesn't provide varImp.
Are there any reason that caretStack doesn't provide varImp?

**Comment by zachmayer** [comment]
caretStack now supports all the S3 clasess of caretEnsemble varImp, plot, dotplot, autoplot, summary, print

https://github.com/zachmayer/caretEnsemble/pull/289
