### ISSUE TITLE
greedy ensemble

### ISSUE THREAD

**Issue by univ12** [zachmayer/caretEnsemble#225]
Hi,
I wonder if greedy ensembling is implemented in this package. The caretEnsemble functions calls caretStack with "method=glm".
In the caretStack description it says "Find a good linear combination of several classification or regression models, using either linear regression, elastic net regression, or greedy optimization",
but I think it's not there.
I think a glm linear combination is fine, just wonder about the description and vignette.

**Comment by zachmayer** [comment]
greedy ensemles are back! 

https://github.com/zachmayer/caretEnsemble/pull/304
https://github.com/zachmayer/caretEnsemble/pull/305
https://github.com/zachmayer/caretEnsemble/pull/306
