### ISSUE TITLE
How does trainControl work with caretEnsemble and caretStack?

### ISSUE THREAD

**Issue by iamdeit** [zachmayer/caretEnsemble#227]
I dont know if it's the expected behavior, but when I use caretEnsemble or caretStack, even if I specify a trainControl with repeatedcv, it creates a lot of samples. If I have 226 observations, each fold has 2260 samples. Does it combine bootstrap + cv?

**Comment by zachmayer** [comment]
this is a question about caret::train, not caretEnsemble.

repeatedcv does repeats of CV.  By default I think its 5 repeats of 10 folds, for 50 total repeats
