### ISSUE TITLE
How to comply with caret's multicore support

### ISSUE THREAD

**Issue by kickbox** [zachmayer/caretEnsemble#230]
I know in caret if I have to enable multi-core support for cross-validation one has to enable multicore through 

```
library(doSNOW)
cl <- makeCluster(ncores)
registerDoSNOW(cl)

my_control <- trainControl(
  ...
  allowParallel = T,
  ...
)

```
If I wanted to enable multi-core for supporting Models, one has to mention `nthread=ncores` in `train()`.

Is this the same in caretEnsemble too?

**Comment by zachmayer** [comment]
Yup, that should work!
