### ISSUE TITLE
   weights of the models

### ISSUE THREAD

**Issue by seymakalay** [zachmayer/caretEnsemble#243]
Hi, I am having hard time to interpret the weights of glm and rpart,
what are the models' weights for glm and rpart?
many thanks in advance,,,

greedy_ensemble <- caretEnsemble(
  model_list, 
  metric="ROC",
  trControl=trainControl(
    number=2,
    summaryFunction=twoClassSummary,
    classProbs=TRUE
    ))
summary(greedy_ensemble)
 **The following models were ensembled: glm, rpart**
They were weighted: 
 **1.4489 -0.9559 -2.0442**
 The resulting ROC is: 0.7573
The fit for each individual model on the ROC is: 
 method       ROC      ROCSD
    glm 0.6829333 0.05890797
   rpart 0.7206765 0.06849524

**Comment by zachmayer** [comment]
This was a problem in 2.0.  The first weight is the intercept: 1.4489 

the glm weight is-0.9559
the rpart weigth is-2.0442

so both models are anti-predictive on your dataset.

3.0 will be better about this
