### ISSUE TITLE
issue #187 (predict fails for models with "custom" names) not solved for xgboost

### ISSUE THREAD

**Issue by danpon** [zachmayer/caretEnsemble#244]
The issue [https://github.com/zachmayer/caretEnsemble/issues/187](https://github.com/zachmayer/caretEnsemble/issues/187) is not fixed for xgboost.

The following R code fails with  Error in eval(predvars, data, env) : object 'xgb' not found
It works if the model is named "xgbTree" instead of  "xgb"

``
require(data.table)
require(caret)
require(caretEnsemble)
data(iris)
iris <- data.table(iris)
iris[, Species := factor(ifelse(Species == "setosa", "SETOSA", sample(c("SETOSA", "OTHERS"), 200, replace = T)))]

set.seed(42)
trainIndex <- createDataPartition(iris$Species, p = .8, list=F)

train <- iris[trainIndex]
test <- iris[-trainIndex]

my_control <- trainControl(
    method="cv",
    number=3,
    index=createResample(train$Species, 3),
    savePredictions="final",
    classProbs=TRUE,
    summaryFunction=twoClassSummary
)

xgb_grid = expand.grid(
    nrounds = 10,
    eta = c(0.1),
    max_depth = c( 2),
    gamma = 1,
    colsample_bytree =0.655, 
    min_child_weight = 1, 
    subsample = 1
)

model_list <- caretList(
    Species~.,
    data=train,
    trControl=my_control,
    metric="ROC",
    tuneList=list(
        xgb=caretModelSpec(method="xgbTree",
                              tuneGrid=xgb_grid),
        rf=caretModelSpec(method="rf",
                          tuneGrid= expand.grid(.mtry = c(round(sqrt(ncol(train))))))
    )
)

greedy_ensemble <- caretEnsemble(
    model_list,
    metric="ROC",
    trControl=trainControl(
        number=2,
        summaryFunction=twoClassSummary,
        classProbs=TRUE
    ))
summary(greedy_ensemble)

predict(greedy_ensemble, newdata=test, type="prob")
``

**Comment by hermandr** [comment]
Hi,

Look at the list of available models in Caret
[https://topepo.github.io/caret/available-models.html](https://topepo.github.io/caret/available-models.html)

No "xgb" only xgbTree, xgbDART, xgbLinear

Herman

**Comment by zachmayer** [comment]
Not reproducible with 4.0:


```R
require(data.table)
require(caret)
require(caretEnsemble)
data(iris)
iris <- data.table(iris)
iris[, Species := factor(ifelse(Species == "setosa", "SETOSA", sample(c("SETOSA", "OTHERS"), 200, replace = T)))]

set.seed(42)
trainIndex <- createDataPartition(iris$Species, p = .8, list=F)

train <- iris[trainIndex]
test <- iris[-trainIndex]

my_control <- trainControl(
method="cv",
number=3,
index=createResample(train$Species, 3),
savePredictions="final",
classProbs=TRUE,
summaryFunction=twoClassSummary
)

xgb_grid = expand.grid(
nrounds = 10,
eta = c(0.1),
max_depth = c( 2),
gamma = 1,
colsample_bytree =0.655,
min_child_weight = 1,
subsample = 1
)

model_list <- caretList(
Species~.,
data=train,
trControl=my_control,
metric="ROC",
tuneList=list(
xgb=caretModelSpec(method="xgbTree",
tuneGrid=xgb_grid),
rf=caretModelSpec(method="rf",
tuneGrid= expand.grid(.mtry = c(round(sqrt(ncol(train))))))
)
)

greedy_ensemble <- caretEnsemble(
model_list,
metric="ROC",
trControl=trainControl(
number=2,
summaryFunction=twoClassSummary,
classProbs=TRUE
))
summary(greedy_ensemble)

predict(greedy_ensemble, newdata=test)
```

```
> predict(greedy_ensemble, newdata=test)
       OTHERS    SETOSA
        <num>     <num>
 1: 0.1585520 0.8414480
 2: 0.1361342 0.8638658
 3: 0.1361342 0.8638658
 4: 0.1361342 0.8638658
 5: 0.1361342 0.8638658
 6: 0.1361342 0.8638658
 7: 0.1585520 0.8414480
 8: 0.1379942 0.8620058
 9: 0.1585520 0.8414480
10: 0.1361342 0.8638658
11: 0.1361342 0.8638658
12: 0.1585520 0.8414480
13: 0.4806919 0.5193081
14: 0.4944327 0.5055673
15: 0.4795527 0.5204473
16: 0.3690919 0.6309081
17: 0.4248919 0.5751081
18: 0.4225127 0.5774873
19: 0.4101127 0.5898873
20: 0.6722663 0.3277337
21: 0.4366719 0.5633281
22: 0.4187927 0.5812073
23: 0.4473127 0.5526873
24: 0.7828535 0.2171465
25: 0.7487535 0.2512465
26: 0.5817463 0.4182537
27: 0.4646727 0.5353273
28: 0.7772735 0.2227265
29: 0.4256127 0.5743873
30: 0.4907127 0.5092873
       OTHERS    SETOSA```
