### ISSUE TITLE
Predict function in CaretEnsemble package returns the error: "object nn not found"

### ISSUE THREAD

**Issue by sfallahpour** [zachmayer/caretEnsemble#246]
I tried to create an ensemble model using the “CaretEnsemble” package. I wrote the following code
 
models2 <- caretList(
  log_sales~., data=train.data.final,
  trControl=trnCtrl,
  
  tuneList=list(
    rf=caretModelSpec(method="rf", tuneGrid=expand.grid(.mtry=c(1:8)) ),  
    nn=caretModelSpec(method="nnet", tuneGrid=expand.grid(.decay = c(0,0.001, 0.01, 0.1, 0.5), .size = c(5:10)), preProcess=c("center", "scale"), 
                      linout=TRUE, trace=FALSE, maxit = 1000),
    gbm=caretModelSpec(method="gbm", tuneGrid=expand.grid(interaction.depth = seq(1, 7, by = 2),
                                                          n.trees = seq(100, 1000, by = 50),
                                                          shrinkage = c(0.01, 0.1), n.minobsinnode = 10) ),
    xgb=caretModelSpec(method="xgbTree", tuneGrid=expand.grid(nrounds = 1000,
                                                              eta = c(0.01,0.05, 0.07, 0.1),
                                                              max_depth = c(4:14),
                                                              gamma=0,
                                                              colsample_bytree = c(0.75),
                                                              subsample = c(0.50),
                                                              min_child_weight =0 ) )
  )
)
 
stack.glm <- caretStack(models2, method="glm",  trControl=trnCtrl)
 
 
Which runs totally fine but when I try to use the stacked model to predict new data I get the following error:
 
pred <- predict(stack.glm, newdata = testing)
**Error in eval(predvars, data, env) : object 'nn' not found**
 
When I run “stack.glm$models$nn” I get the results for neural network but I am not sure if object “nn” in the error message refers to same thing.

**Comment by zachmayer** [comment]
cannot reproduce with 4.0:

```R
library(caretEnsemble)
library(caret)
library(randomForest)
library(nnet)
library(gbm)

# Set seed for reproducibility
set.seed(123)

# Split the iris dataset
data(iris)
inTrain <- createDataPartition(iris$Sepal.Length, p = 0.7, list = FALSE)
training <- iris[inTrain,]
testing <- iris[-inTrain,]

# Create model list
models <- caretList(
  Sepal.Length ~ .,
  data = training,
  tuneList = list(
    rf = caretModelSpec(method = "rf", tuneGrid = expand.grid(.mtry = c(2, 3))),
    nn = caretModelSpec(
        method = "nnet", 
        tuneGrid = expand.grid(.decay = c(0, 0.1), .size = c(3, 5)),
        trace = FALSE),
    gbm = caretModelSpec(
        method = "gbm", 
        tuneGrid = expand.grid(interaction.depth = c(1, 3),
        n.trees = c(50, 100),
        shrinkage = 0.1,
        n.minobsinnode = 10),
        verbose = FALSE)
  )
)

# Stack models
stack.glm <- caretStack(models, method = "glm")
pred <- predict(stack.glm, newdata = testing)
head(pred)
```
