### ISSUE TITLE
CaretEnsemble with pretrained models

### ISSUE THREAD

**Issue by KhalilM94** [zachmayer/caretEnsemble#258]
Hello
I have already pre-trained a few models using rfe (recursive feature elimination) in caret. Is there any way to use CaretEnsemble with my models to stack them into a single random forest predictor?

**Comment by zachmayer** [comment]
I *think* caretEnsemble works ok with custom caret models.  Write a custom model where the "train" step does nothing but the predict step makes predictions.  Provide some data (be sure it is NOT the training data you used for pretraining) and caretEnsemble can make predictions on that data and then use those predictions to make an ensemble.

The key element is out-of-sample predictions, so you'll need a custom model to make predictions and data to predict on.

**Comment by zachmayer** [comment]
caretEnsemble does work with custom models, see https://github.com/zachmayer/caretEnsemble/pull/310
