### ISSUE TITLE
Differences between caret y caretensemble

### ISSUE THREAD

**Issue by jsalinas69** [zachmayer/caretEnsemble#342]
Greetings from Lima, Peru
I have a question. I am training a data with models (Bagging, Naive Bayes, Logistic Regression and k-nn) usign **caret**

fitControl1  <- trainControl(method = "cv",
                             number = 10,
                             savePredictions = 'final',
                             classProbs = T)

set.seed(2024) 
modelo_bg <- train(training[, predictores], # RIESGO ~ .
                   training[, target],
                   method = 'treebag',
                   trControl = fitControl1,
                   metric = "Accuracy",
                   tuneLength = 3)
modelo_bg
test$clase_bg  <- predict(object = modelo_bg, 
                          test[, predictores])
cm_bg <- caret::confusionMatrix(test$clase_bg,
                                test[, target],
                                positive = pos)
cm_bg$byClass["Sensitivity"] 
cm_bg$byClass["Specificity"] 
cm_bg$overall["Accuracy"]

set.seed(2024) 
modelo_nb <- train(training[, predictores],
                   training[, target],
                   method = 'nb',
                   trControl = fitControl1,
                   metric = "Accuracy",
                   tuneLength = 3)

modelo_nb
test$clase_nb <- predict(object = modelo_nb, 
                         test[, predictores])
cm_nb <- caret::confusionMatrix(test$clase_nb,
                                test[, target],
                                positive = pos)
cm_nb$byClass["Sensitivity"] 
cm_nb$byClass["Specificity"] 
cm_nb$overall["Accuracy"]

set.seed(2024) 
modelo_rl <- train(training[, predictores],
                   training[, target],
                   method = 'glm', family = "binomial",
                   trControl = fitControl1,
                   metric = "Accuracy",
                   tuneLength = 3)
modelo_rl
test$clase_rl <- predict(object = modelo_rl, test[, predictores])
cm_rl <- caret::confusionMatrix(test$clase_rl,
                                test[, target],
                                positive = pos)
cm_rl$byClass["Sensitivity"] 
cm_rl$byClass["Specificity"] 
cm_rl$overall["Accuracy"]

set.seed(2024) 
modelo_knn <- train(training[, predictores],
                    training[, target],
                    method = 'knn', 
                    trControl = fitControl1,
                    metric = "Accuracy",
                    tuneLength = 3)
modelo_knn
test$clase_knn <- predict(object = modelo_knn, 
                          test[, predictores])
cm_knn <- caret::confusionMatrix(test$clase_knn,
                                 test[, target],
                                 positive = pos)
cm_knn$byClass["Sensitivity"] 
cm_knn$byClass["Specificity"] 
cm_knn$overall["Accuracy"]

These are the results in training with k-nn

No pre-processing
Resampling: Cross-Validated (10 fold) 
Summary of sample sizes: 2594, 2593, 2594, 2593, 2594, 2594, ... 
Resampling results across tuning parameters:

  k  Accuracy  Kappa
  5  0.858     0.600
  7  0.863     0.614
  9  0.862     0.613

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was **k = 7.**

model_list = list(Bagging     = modelo_bg,
                  Naive_Bayes = modelo_nb,
                  Logistica   = modelo_rl,
                  knn         = modelo_knn)

comparacion_modelos <- resamples(model_list)
descrCor1 <- modelCor(comparacion_modelos)  
descrCor1

And this are results about the correlation matrix using caret

                   Bagging Naive_Bayes Logistica     knn
Bagging       1.00000       0.360  -0.00448  0.4528
Naive_Bayes  0.35990       1.000   0.64979  0.5377
Logistica      -0.00448       0.650   1.00000 -0.0338
knn                0.45276       0.538  -0.03385  1.0000

However, using caretEnsemble

fitControl2   <- trainControl(method = "cv",
                              number = 10,
                              savePredictions = 'final',
                              classProbs = T)
modelos = list(
  treebag  =  caretModelSpec(method = "treebag",
                             tuneLength = 3),
  nb       =  caretModelSpec(method = "nb", 
                             tuneLength = 3),
  glm      =  caretModelSpec(method = "glm",
                             family = "binomial",
                             tuneLength = 3),
  knn      =  caretModelSpec(method = "knn", 
                             tuneLength = 3)
               )

set.seed(2024) 
modelo_ensamble <- caretList(training[, predictores],
                             training[, target],
                             trControl = fitControl2,
                             tuneList = modelos,
                             metric = "Accuracy")

modelo_ensamble

modelo_ensamble$treebag
modelo_ensamble$nb
modelo_ensamble$glm
modelo_ensamble$knn

Obtain this results in k-nn

k-Nearest Neighbors 

No pre-processing
Resampling results across tuning parameters:

  k  Accuracy  Kappa
  5  0.853     0.590
  7  0.867     0.627
  9  0.867     0.626

Accuracy was used to select the optimal model using the largest value.
The final value used for the model was **k = 9.**

And these results about the correlation matrix
 
resultados <- resamples(modelo_ensamble)
summary(resultados)
descrCor2 <- modelCor(resultados)
descrCor2

            treebag     nb      glm      knn
treebag   1.000  0.260 -0.14247 -0.50580
nb           0.260  1.000 -0.22076 -0.26789
glm        -0.142 -0.221  1.00000  0.00676
knn        -0.506 -0.268  0.00676  1.00000

¿Why the difference if you are using the same seed (set.seed(2024) and the same training procedure (traincontrol()? 

Thank you very much

**Comment by zachmayer** [comment]
How much of this code can you remove while replicating the problem?  Can you make the example fully reproducible using the iris dataset or another built-in?

**Comment by jsalinas69** [comment]
Hello, I am sharing my code and my data so that you can see the error by comparing the output I get on line 177 and line 250
[RISK.zip](https://github.com/user-attachments/files/17856104/RISK.zip)
. I get equally different results when working with other data such as Titanic, Iris, etc.. Thanks.

**Comment by zachmayer** [comment]
I'm not going download that zip file.  Please put **minimal** reproducible code in this issue that I can cut/paste into R to replicate the issue.

**Comment by zachmayer** [comment]
Try with the new version I just pushed to main, with aggregate_resamples=FALSE
