### ISSUE TITLE
Add parallel option to predict.caretStack using foreach

### ISSUE THREAD

**Issue by zachmayer** [zachmayer/caretEnsemble#60]

**Comment by terrytangyuan** [comment]
Hi Zach, is this issue fixed now? I can probably help you with this. I am thinking sticking with `apply` for small data set and change to `foreach` for large data set.

**Comment by zachmayer** [comment]
I'd be happy to get a pull request!

**Comment by terrytangyuan** [comment]
Sure, but it looks like there are bugs in `caretEnsemble`? I ran the example code from `predict.caretEnsemble` both on iris data set and my own data set. Could you check? 
The error is as follows:
```
Error in setkeyv(value, key) : 
  4 arguments passed to .Internal(nchar) which requires 3
```

**Comment by terrytangyuan** [comment]
Actually, I cleaned my environment and there's no more bug. But if I load each source file in your /R folder and then use those methods, the error will happen again. Do you know why?

**Comment by zachmayer** [comment]
try using `devtools::load_all()` instead.

**Comment by zachmayer** [comment]
Then do `devtools::test()` and `devtools::check()` when you're done writing code.
