### ISSUE TITLE
trim.caretList, trim.caretEnsemble, and trim.caretStack methods

### ISSUE THREAD

**Issue by jknowles** [zachmayer/caretEnsemble#69]
I'd like to see us add a function that prunes the train models stored in the `caretEnsemble` object. There is a lot of stuff stored in these individual train objects that takes up a lot of space and is not necessary for doing predictions or diagnostics. This is especially a problem when training models with a large number of observations (50k+). 

This is an example of how much can be saved from a `glm` object and an approach we might want to take here: http://www.win-vector.com/blog/2014/05/trimming-the-fat-from-glm-models-in-r

**Comment by zachmayer** [comment]
A version of this function may show up in `caret`, in which case we just need to write methods for `caretList`, `caretStack`, and `caretEnsemble`.

**Comment by jknowles** [comment]
That sounds good. I'd be happy to help with the effort in `caret` to improve that as well.

**Comment by zachmayer** [comment]
See here:
https://github.com/topepo/caret/issues/90
https://github.com/topepo/caret/commit/9a4f7965594d034e565e89ade9459c9c6be828a1
https://github.com/topepo/caret/commit/482efce3131f13b371082a35283638815d8240a0

Max will be happy to take any PRs you submit.

**Comment by zachmayer** [comment]
Here's how this is going to work:

1. The trim code for base models will live in the `getModelInfo()` function in caret.  This allows all the fitting, prediction, trimming, etc. code for a given model to live in one place in the caret ecosystem. To add new trim methods, submit a PR to caret.
2. caret now has a `trim` S3 generic, and a `trim.train` method (which trims the caret object as well as the final model in the trainobject).
3. caretEnsemble will have `trim` methods for `caretList`, `caretEnsemble`, and `caretStack`.  These will remove unnecessary parts of the object, then call `trim.train` on any caret models.  `caretEnsemble` and `caretStack` will call `trim.caretList` on the underlying list of models.

See here for the trim S3 generic:
https://github.com/topepo/caret/commit/35852d4c1c7c0e407721e049ca0160ffe349138a

**Comment by jknowles** [comment]
@zachmayer Good work. This is an absolutely awesome enhancement to our package -- which by the way has been getting a lot of good kudos from folks on the web.

**Comment by zachmayer** [comment]
glad to hear it!

**Comment by zachmayer** [comment]
I am now trimming some data by default during model fitting in caretList.

you can also use the built in trim methods in caret for a stack or ensemble
