### ISSUE TITLE
Large datasets

### ISSUE THREAD

**Issue by jknowles** [zachmayer/caretEnsemble#70]
I'm not sure how common folks are using `train` on large datasets, but my use case for `caretEnsemble` involves models with a minimum of 40k training observations. In this environment, we might need some additional checks built into the methods for `caretEnsemble` to enable them to make sense / perform well with these large models. 

Primarily this is an issue currently for `autoplot.caretEnsemble` which makes a great looking residual plot, but plotting 40k residuals takes far too long and is not useful. Needs a statement like 

```
if(nobs > 1000){
     plotdf <- sample(plotdf, ... 1000)
}

```

I'll build this in and submit a PR.

**Comment by zachmayer** [comment]
I'm still using do.call, but I moved most of the internals to data.table.  I will test with some larger datasets

**Comment by zachmayer** [comment]
closed in favor of https://github.com/zachmayer/caretEnsemble/issues/309
