### ISSUE TITLE
Multi-class classification greedy optimization 

### ISSUE THREAD

**Issue by thomaskern** [zachmayer/caretEnsemble#8]
i see that branch Dev has some more progress regarding multi-class classification ensemble stacking but unfortunately it is not yet done.
do you plan on implementing this and/or could you point me in the right direction so i might be able to finish it? I don't seem to understand what the problem/holdup is (no offense intended)

**Comment by ajing** [comment]
Is there any quick way to hack the multiclass classification with greedy optimization? I am participating a kaggle competition...

**Comment by zachmayer** [comment]
The quickest way would be to use `caretStack` with `glmnet` as the stacker.

In general, I find myself using `caretStack` more than `caretList`.  It's a lot more flexible, and if you use `method='glm'` you'll get almost the exact same results as with a greedy ensemble.

Take a look at the vignette for some examples: http://htmlpreview.github.io/?https://github.com/zachmayer/caretEnsemble/blob/master/inst/doc/caretEnsemble-intro.html

**Comment by zachmayer** [comment]
@ajing The real key is the optimization function.  I haven't even thought of a hack that will work here.... Once someone's written the multiclass optimization function work, we can work on multiclass greedy ensembling.

**Comment by ajing** [comment]
In methodList=c('rpart', 'nnet'), could I specify a new model as a variable? Because, for xgboost, caret hasn't include that yet, but they can specific a variable modelInfo for xgboost for train function. Could I do something like methodList = c(modelInfo, 'nnet')?

**Comment by zachmayer** [comment]
We don't support that yet, but it's definitely on the to-do list.

For now, you can fit the model separately with a call to `caret::train`, and then add it to the list.  To quote from [the vignette](http://htmlpreview.github.io/?https://github.com/zachmayer/caretEnsemble/blob/master/inst/doc/caretEnsemble-intro.html) (please do read it!):

>Finally, you should note that caretList does not support custom caret models. Fitting those models are beyond the scope of this vignette, but if you do so, you can manually add them to the model list (e.g. `model_list_big[['my_custom_model']] <- my_custom_model)`. Just be sure to use the same re-sampling indexes in trControl as you use in the caretList models!

**Comment by ajing** [comment]
Sorry to ask the question again... For multiclass classification, is that possible to build the ensemble model? I got the error for caretStack with glmnet also...

> stack_model <- caretStack(model_list, method='glmnet')                                                                                                                                                         
Error in check_caretList_model_types(list_of_models) : 
  Not yet implemented for multiclass problems

**Comment by zachmayer** [comment]
Darn.  I thought I'd fixed that.




Ok, multi class for caretStack should be easier implement than for caretEnsemble.  I'll take a look.




No promises on when I can get to it!



—

**Comment by ajing** [comment]
For adding a new customized model, 
In the example:
"Just be sure to use the same re-sampling indexes in trControl as you use in the caretList models!"

What portion I need to change in modelInfo to use the same resampling indexes?

I use the modelInfo of xgboost provided by topepo.

**Comment by zachmayer** [comment]
Lets say x is your other model (the one you're ensembling xgboost with): 
```{R}
new_train_control <- trainControl(index=x$control$index, indexOut=x$control$indexOut)
```

Use the new control to fit your xgboost model.

**Comment by ajing** [comment]
Thanks! I was thinking about still using caretEnsemble framework. Can I do something like:
```
my_control <- trainControl(
  method='boot',
  number=25,
  classProbs=TRUE,
  index=createResample(training$Class, 25),
  summaryFunction=twoClassSummary
)

model_list <- caretList(
  Class~., data=training,
  trControl=my_control,
  tuneList=list(
    rf1=caretModelSpec(method='rf', tuneGrid=data.frame(.mtry=2)),
    xgb = caretModelSpec(method=modelInfo, tuneLength = 3)
  )
```

**Comment by zachmayer** [comment]
[As explained in the vignette: "you should note that caretList does not support custom caret models"](https://htmlpreview.github.io/?https://github.com/zachmayer/caretEnsemble/blob/master/inst/doc/caretEnsemble-intro.html)

You have to fit the second model with a second call to train.  E.g.:
```{R}
my_control <- trainControl(
  method='boot',
  number=25,
  classProbs=TRUE,
  index=createResample(training$Class, 25),
  summaryFunction=twoClassSummary
)

model_list <- caretList(
  Class~., data=training,
  trControl=my_control,
  tuneList=list(
    rf1=caretModelSpec(method='rf', tuneGrid=data.frame(.mtry=2))
  )

new_model <- train(Class~., data=training, trControl=my_control, method=modelInfo, tuneLength = 3)

model_list$xgb <- new_model
```

**Comment by ajing** [comment]
Thanks for the code! Yes, it works now.

**Comment by zachmayer** [comment]
Good!  Glad to help

**Comment by ajing** [comment]
Sorry to bother again.. I got the following error, because some assumption about method variable.. 

> model_list$xgb <- new_model
> greedy_ensemble <- caretEnsemble(model_list)
Error in paste("Model '", method, "' is not in the ", "set of existing models",  : 
  object 'method' not found

**Comment by zachmayer** [comment]
crap.  that's a bug.  If you can make a simple test case, I'll add it to the queue to fix.

**Comment by ajing** [comment]
This could be a test case:

```R
training = data.frame(matrix(runif(120),nrow=20,ncol=6), Class = factor(sample(c("Yes", "No"), 20, replace=T)))
my_control <- trainControl(
  method='boot',
  number=5,
  savePredictions=TRUE,
  classProbs=TRUE,
  index=createResample(training$Class, 5),
  summaryFunction=twoClassSummary
)
model_list <- caretList(
  Class~., data=training,
  trControl=my_control,
  methodList=c('glm', 'rpart')
)
new_model <- train(Class~., data=training, trControl=my_control, method=modelInfo, metric = "ROC", tuneGrid = expand.grid(eta = 0.01,max_depth = 5, nrounds=100))
model_list$xgb <- new_model

greedy_ensemble <- caretEnsemble(model_list)
```

**Comment by ajing** [comment]
Is there any recommended way to add a new caret model to existing model_list?

Like, I have a model_list, and I want to add a new model:

I can do
```R
model9 <- train(X[train,], Y[train], method='gam', trControl=myControl)
```

Then, 
```R
model_list$gam = model9
```

Is this right?

**Comment by zachmayer** [comment]
Yup!



—

**Comment by tsuresh83** [comment]
@ajing 
I had the same issue.  I have a dirty workaround that works for me.  The function 'makePredObsMatrix' in the caretEnsemble package is throwing the error.  Below is the source code of the function with the initial two lines commented (these are just checks.  I assume if you know what you're doing, uncommenting this is fine - perhaps @zachmayer can throw more light).  I sourced the modified function and added the following lines to my script. It worked.  Hope it helps.
######
source('/media/3TB/kag/caretEnsemble-master/R/helper_functions.R')
assignInNamespace("makePredObsMatrix",makePredObsMatrix, ns="caretEnsemble")
#######
######modified the function in helper_function.R file from caretEnsemble repo
makePredObsMatrix <- function(list_of_models){
  
  #caretList Checks
  #check_caretList_classes(list_of_models)
  #check_caretList_model_types(list_of_models)
  
  #Make a list of models
  modelLibrary <- extractBestPreds(list_of_models)
  model_names <- names(modelLibrary)
  
  #Model library checks
  check_bestpreds_resamples(modelLibrary) #Re-write with data.table?
  check_bestpreds_indexes(modelLibrary) #Re-write with data.table?
  check_bestpreds_obs(modelLibrary) #Re-write with data.table?
  check_bestpreds_preds(modelLibrary) #Re-write with data.table?
  
  #Extract model type (class or reg)
  type <- extractModelTypes(list_of_models)
  
  #Add names column
  for(i in seq_along(modelLibrary)){
    set(modelLibrary[[i]], j="modelname", value=names(modelLibrary)[[i]])
  }
  
  #Remove parameter columns
  keep <- Reduce(intersect, lapply(modelLibrary, names))
  for(i in seq_along(modelLibrary)){
    rem <- setdiff(names(modelLibrary[[i]]), keep)
    if(length(rem) > 0){
      for(r in rem){
        set(modelLibrary[[i]], j=r, value=NULL)
      }
    }
  }
  modelLibrary <- rbindlist(modelLibrary, fill=TRUE)
  
  #For classification models that produce probs, use the probs as preds
  #Otherwise, just use class predictions
  if (type=="Classification"){
    positive <- as.character(unique(modelLibrary$obs)[2]) #IMPROVE THIS!
    pos <- as.numeric(modelLibrary[[positive]])
    good_pos_values <- which(is.finite(pos))
    set(modelLibrary, j="pred", value=as.numeric(modelLibrary[["pred"]]))
    set(modelLibrary, i=good_pos_values, j="pred", value=modelLibrary[good_pos_values,positive,with=FALSE])
  }
  
  #Reshape wide for meta-modeling
  modelLibrary <- data.table::dcast.data.table(
    modelLibrary,
    obs + rowIndex + Resample ~ modelname,
    value.var = "pred"
  )
  
  #Return
  return(list(obs=modelLibrary$obs, preds=as.matrix(modelLibrary[,model_names,with=FALSE]), type=type))
}

**Comment by zachmayer** [comment]
@tsuresh83  Could you make a PR on github with the new version of your function so I can see what you changed?  If the fix looks good to me and @jknowles I'll merge it into master.

**Comment by tsuresh83** [comment]
@zachmayer I am afraid this is not a fix.  From what I've seen the actual fix could be the addition of an entry needs to be added to the list of models in 'models.RData' from the caret package.  What I suggested is only stop gap measure until the actual fix.

**Comment by nithum** [comment]
Has there been any progress or workarounds developed for using caretStack for multi-class classfication?

**Comment by zachmayer** [comment]
Nope, but I welcome pull requests! 

At the moment we're in the middle of some code cleanup and bug fixes, which will probably be followed by a CRAN release.  Then I'll figure out how to get caretList and caretStack to work with multiclass.

Getting caretEnsemble to work with multiclass will be harder.

**Comment by nithum** [comment]
Thanks for the quick response @zachmayer! By the way, what is your reference material for the implementation of Stacking? Are you using "Elements of Statistical Learning" or something?

**Comment by zachmayer** [comment]
Hmmm, I don't really have a reference I recall.  It's pretty simple actually: I just use the out-of-sample predictions from `caret::train(..., trControl=trainControl(savePredictions=TRUE))` to train the next model.

It's not super sophisticated, but it works.

**Comment by nithum** [comment]
@zachmayer - thanks for the help. I just wanted to let you know that I managed to implement caretStack for a multi-class classification for a project that I'm working on. It's a bit hacky, but it works. I'd love to contribute it to your repository but I'm new to coding and this'd be my first contribution to a project. Could I chat with you or @jknowles at some point about how to best merge it with your codebase.

**Comment by zachmayer** [comment]
@ajing @nithum Could one of you checkout the latest master and confirm that this bug still occurs?

**Comment by ajing** [comment]
When I was trying to reinstall caretEnsemble, it says:

```
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'pbkrtest'
ERROR: lazy loading failed for package 'caretEnsemble'
* removing 'C:/Users/ajing/Documents/R/win-library/3.2/caretEnsemble'
```

**Comment by zachmayer** [comment]
Restart R (and maybe restart your computer too), then:
```{R}
remove.packages('caretEnsemble')
install.packages('caretEnsemble')
```

**Comment by ajing** [comment]
I don't know why it doesn't work on windows, but I get the installation right on ubuntu system. I have the following error, but I may do it in the wrong way.

```
> training = data.frame(matrix(runif(120),nrow=20,ncol=6), Class = factor(sample(c("Yes", "No"), 20, replace=T)))
> my_control <- trainControl(
+   method='boot',
+   number=5,
+   savePredictions=TRUE,
+   classProbs=TRUE,
+   index=createResample(training$Class, 5),
+   summaryFunction=twoClassSummary
+ )
> model_list <- caretList(
+   Class~., data=training,
+   trControl=my_control,
+   methodList=c('glm', 'rpart')
+ )
Loading required package: rpart
Warning messages:
1: In train.default(x, y, weights = w, ...) :
  The metric "Accuracy" was not in the result set. ROC will be used instead.
2: glm.fit: algorithm did not converge 
3: glm.fit: fitted probabilities numerically 0 or 1 occurred 
4: glm.fit: algorithm did not converge 
5: glm.fit: fitted probabilities numerically 0 or 1 occurred 
6: In train.default(x, y, weights = w, ...) :
  The metric "Accuracy" was not in the result set. ROC will be used instead.
> new_model <- train(Class~., data=training, trControl=my_control, method=modelInfo, metric = "ROC", tuneGrid = expand.grid(eta = 0.01,max_depth = 5, nrounds=100))
Loading required package: xgboost
Loading required package: plyr
> model_list$xgb <- new_model
> 
> greedy_ensemble <- caretEnsemble(model_list)
Error in paste("Model '", method, "' is not in the ", "set of existing models",  : 
  object 'method' not found

```

**Comment by zachmayer** [comment]
That's a 2-class example.  Here's a 3-class example, which currently fails:
```{R}
library(caretEnsemble)
data(iris)
my_control <- caret::trainControl(
  method='boot',
  number=5,
  savePredictions="final",
  classProbs=TRUE,
  index=caret::createResample(iris$Species, 5)
)
model_list <- caretList(
  x=iris[,-5],
  y=iris[,5],
  trControl=my_control,
  methodList=c('glmnet', 'rpart')
)

ens <- caretStack(model_list, method='rpart')
```

**Comment by ajing** [comment]
Yes.

```
Error in check_caretList_model_types(list_of_models) : 
  Not yet implemented for multiclass problems
```

**Comment by zachmayer** [comment]
Also, I cleaned up your example, and it runs fine for me:
```{R}
library(caretEnsemble)
library(caret)
training = data.frame(matrix(runif(120),nrow=20,ncol=6), Class = factor(sample(c("Yes", "No"), 20, replace=T)))
my_control <- trainControl(
  method='boot',
  number=5,
  savePredictions=TRUE,
  classProbs=TRUE,
  index=createResample(training$Class, 5),
  summaryFunction=twoClassSummary
)
model_list <- caretList(
  Class~., data=training,
  trControl=my_control,
  methodList=c('glm', 'rpart')
)
```

Make sure you're using the latest version of caretEnsemble.

**Comment by ajing** [comment]
That example is for adding a new model, which is not included in caret.

**Comment by zachmayer** [comment]
@ajing This issue is for running `caretStack` with multiclass models.  Custom model support in caretList is a different issue: https://github.com/zachmayer/caretEnsemble/issues/109

**Comment by ajing** [comment]
I began with asking multiclass, then asked something else... So, multi-class is working?

**Comment by zachmayer** [comment]
No, but it will be soon.  Please use separate issues for separate discussions in the future.

**Comment by ajing** [comment]
Sure.

**Comment by kprimice** [comment]
Any update on multiclass models?

**Comment by zachmayer** [comment]
See pending PR here: https://github.com/zachmayer/caretEnsemble/pull/191

The basic concept works, but I still need to re-write all the intermediate functions to return (and operate) on matrices in the multiclass case.

**Comment by kprimice** [comment]
Thank you, can't wait for the release!

**Comment by grepinsight** [comment]
Was looking for multiclass ensembl method, and google search led me here. 
Can't wait for multiclass ensemble as well!

**Comment by zee86** [comment]
Hi Zack,
May I ask please , is there any way around that I can use CaretEnsemble with different training dataset ?

**Comment by zachmayer** [comment]
@zee86 It still doesn't work with multiclass

**Comment by zee86** [comment]
Thank you very much for the reply. I am very sorry if my next question going to sound very naive to you and a waste of time, but I am truly not expert and trying to learn to do it. 
so is it mean having this error from the following code , is because caretEnsemble does not support multiclass? and is there any R package you may know can allow me to do the ensemble of those different trained models ?

Error in check_bestpreds_obs(modelLibrary) : 
      Observed values for each component model are not the same.  Please re-train the models with the same Y variable


        library(mice)
        library(e1071)
        library(caret)
        library("caretEnsemble")
    
    data <- iris
    #Generate 10% missing values at Random 
    iris.mis <- prodNA(iris, noNA = 0.1)
    #remove categorical variables
    iris.mis <- subset(iris.mis, select = -c(Species))
    
    # 5 Imputation using mice pmm
    
    imp <- mice(iris.mis, m=5, maxit = 10, method = 'pmm', seed = 500)
    
    # save 5 imputed dataset.
    x1 <- complete(imp, action = 1, include = FALSE)
    x2 <- complete(imp, action = 2, include = FALSE)
    x3 <- complete(imp, action = 3, include = FALSE)
    x4 <- complete(imp, action = 4, include = FALSE)
    x5 <- complete(imp, action = 5, include = FALSE)
    
    ## Apply the following method for each imputed set 
  
    form <- iris$Sepal.Width # target coloumn
    n <- nrow(x1)  # since all data sample are the same length
    prop <- n%/%fold
    set.seed(7)
    newseq <- rank(runif(n))
    k <- as.factor((newseq - 1)%/%prop + 1)
    i<-1
    CVfolds <- 10
    CVrepeats <- 3
      indexPreds <- createMultiFolds(x1[k != i,]$Sepal.Width, CVfolds, CVrepeats)
      ctrl <- trainControl(method = "repeatedcv", repeats = CVrepeats,number = CVfolds, returnResamp = "all", savePredictions = "all", index = indexPreds)

    fit1 <- train(Sepal.Width ~., data = x1[k !=i, ],method='svmLinear2',trControl = ctrl)
    fit2 <- train(Sepal.Width ~., data = x2[k != i, ],method='svmLinear2',trControl = ctrl)
    fit3 <- train(Sepal.Width ~., data = x3[k != i, ],method='svmLinear2',trControl = ctrl)
    fit4 <- train(Sepal.Width ~., data = x4[k != i, ],method='svmLinear2',trControl = ctrl)
    fit5 <- train(Sepal.Width ~., data = x5[k != i, ],method='svmLinear2',trControl = ctrl)
    #combine the created model to a list
          svm.fit <- list( fit1,  fit2,  fit3,  fit4,  fit5)
    
      # convert the list to cartlist
      class(svm.fit) <- "caretList" 
    
      #create the ensemble where the error occur.
      svm.all <- caretEnsemble(svm.fit,method='svmLinear2')

Additional note:  basically the above code is creating five imputed dataset then apply SVM to each imputed dataset using the train function in caret, then ensemble the resulted training model using caretEnsemble.  to be able at the end to predict each test set using the ensemble model.

**Comment by zachmayer** [comment]
This has nothing to do with multiclass.  Please open a new issue.

**Comment by shreyaa94** [comment]
I have a problem in using varImp for continuous response variable under caretensemble.I have used nnet,gbm and rf for ensembling.Error is showing like "Error in varImp[, "%IncMSE"] : subscript out of bounds".

**Comment by shreyaa94** [comment]
is varImp not applicable for continuous response case?
while using caretEnsemble I have this warning also "In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures."

**Comment by zachmayer** [comment]
@shreyaa94 Please post a [reproducible example](https://stackoverflow.com/a/5963610/345660) in the [caret repo](https://github.com/topepo/caret/issues). (`varImp` is a caret function).

**Comment by zachmayer** [comment]
@shreyaa94 `There were missing values in resampled performance measures` It's generally ok if a couple models fail, which is what that warning tells you.

**Comment by JackHo327** [comment]
@zachmayer 
Hey Zach, I am new to caretEnsemble, and I met the almost same problem as above. 

```{r}
library("caret")
library("mlbench")
library("pROC")
data(Sonar)

# I manually add one more category to `Class` varibale
sed.seed(123)
index <- as.integer(runif(n = 60,min = 1,max = 208))
Sonar$Class <- as.character(Sonar$Class)
Sonar$Class[index] <- "Q"
Sonar$Class <- as.factor(Sonar$Class)

# now there are three levels in Class
# [1] Q R Q Q R R R R R R R Q R R R R Q Q R R R R R R R Q Q Q R Q R R R Q R R R R R R Q R R R R ...
# Levels: M Q R

set.seed(107)
inTrain <- createDataPartition(y = Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTrain,]
testing <- Sonar[-inTrain,]
my_control <- trainControl(
      method="boot",
      number=25,
      savePredictions="final",
      classProbs=TRUE,
      index=createResample(training$Class, 25)
)

library("rpart")
library("caretEnsemble")
model_list <- caretList(
      Class~., data=training,
      trControl=my_control,
      tuneList = list(gbm = caretModelSpec(method = "gbm", verbose = F, tuneGrid = expand.grid(.n.trees = 100, .interaction.depth = 11, .shrinkage = 0.001, .n.minobsinnode = 10)), rf = caretModelSpec(method = "rf", ntree = 100), rpart = caretModelSpec(method = "rpart")
))

glm_ensemble <- caretStack(
      model_list,
      method="glm",
      metric="ROC",
      trControl=trainControl(
            method="boot",
            number=10,
            savePredictions="final",
            classProbs=TRUE,
            summaryFunction=twoClassSummary
      )
)
```

Then I will get an error message:

    Error in check_caretList_model_types(list_of_models) : 
      Not yet implemented for multiclass problems

I've noticed that this is still an open issue, I thought it might be not easy to solve, so could you gave me several recommendations about is there any other packages in R could help me to stack models quickly and conveniently?

Thanks for you time ;p

**Comment by zachmayer** [comment]
I don't know of a package that lets you stack multiclass models.  Maybe take a look at MLR?

https://github.com/mlr-org/mlr

**Comment by zachmayer** [comment]
I haven’t continued working on it yet

**Comment by zachmayer** [comment]
PR to add multiclass here: https://github.com/zachmayer/caretEnsemble/pull/260

**Comment by zachmayer** [comment]
caretStack now supports multiclass!
